Repository HeartVera/HeartVera, pull requests merged in 2024-06, with the labels that each got.

#5 [2024/06/19] feat/swagger >> 스웨거 적용
  build.gradle
  src/main/java/com/sparta/heartvera/config/SwaggerConfig.java
  src/main/java/com/sparta/heartvera/security/config/WebSecurityConfig.java
Labels: 🌟 feat

#6 [2024/06/19] feat/register >> 회원가입 구현 및 PasswordEncoder bean추가
  src/main/java/com/sparta/heartvera/domain/auth/controller/AuthController.java
  src/main/java/com/sparta/heartvera/domain/auth/dto/SignupRequestDto.java
  src/main/java/com/sparta/heartvera/domain/auth/service/AuthService.java
  src/main/java/com/sparta/heartvera/domain/user/entity/User.java
  src/main/java/com/sparta/heartvera/security/config/WebSecurityConfig.java
  src/main/java/com/sparta/heartvera/security/service/UserDetailsImpl.java
Labels: 🌟 feat

#10 [2024/06/19] feat/exception-init >> Exception 초기 파일 생성
  src/main/java/com/sparta/heartvera/common/exception/CustomException.java
  src/main/java/com/sparta/heartvera/common/exception/ErrorCode.java
  src/main/java/com/sparta/heartvera/common/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/heartvera/common/exception/dto/ExceptionResponse.java
Labels: 🌟 feat

#8 [2024/06/19] feat/post >> 게시판 CRUD 기능 구현
  src/main/java/com/sparta/heartvera/domain/post/controller/PostController.java
  src/main/java/com/sparta/heartvera/domain/post/dto/PostRequestDto.java
  src/main/java/com/sparta/heartvera/domain/post/dto/PostResponseDto.java
  src/main/java/com/sparta/heartvera/domain/post/entity/Post.java
  src/main/java/com/sparta/heartvera/domain/post/repository/PostRepository.java
  src/main/java/com/sparta/heartvera/domain/post/service/PostService.java
Labels: 🌟 feat

#12 [2024/06/19] feat/post >> 예외처리 변경, 익명 게시판으로 변경
  src/main/java/com/sparta/heartvera/domain/post/dto/PostResponseDto.java
  src/main/java/com/sparta/heartvera/domain/post/service/PostService.java
Labels: ♻️ refactor

#15 [2024/06/19] feat/login >> 로그인구현, JwtAuthenticationFilter 구현
  src/main/java/com/sparta/heartvera/domain/auth/controller/AuthController.java
  src/main/java/com/sparta/heartvera/domain/auth/dto/LoginRequestDto.java
  src/main/java/com/sparta/heartvera/domain/post/controller/PostController.java
  src/main/java/com/sparta/heartvera/domain/post/dto/PostRequestDto.java
  src/main/java/com/sparta/heartvera/domain/post/dto/PostResponseDto.java
  src/main/java/com/sparta/heartvera/domain/post/entity/Post.java
  src/main/java/com/sparta/heartvera/domain/post/repository/PostRepository.java
  src/main/java/com/sparta/heartvera/domain/post/service/PostService.java
  src/main/java/com/sparta/heartvera/security/config/WebSecurityConfig.java
  src/main/java/com/sparta/heartvera/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/sparta/heartvera/security/util/JwtUtil.java
Labels: 🌟 feat

#21 [2024/06/20] feat/post >> 일반 게시판 추가
  src/main/java/com/sparta/heartvera/domain/post/controller/PublicPostController.java
  src/main/java/com/sparta/heartvera/domain/post/dto/PublicPostResponseDto.java
  src/main/java/com/sparta/heartvera/domain/post/entity/PublicPost.java
  src/main/java/com/sparta/heartvera/domain/post/repository/PublicPostRepository.java
  src/main/java/com/sparta/heartvera/domain/post/service/PublicPostService.java
  src/main/java/com/sparta/heartvera/security/config/WebSecurityConfig.java
Labels: 🌟 feat

#19 [2024/06/20] feat/refreshtoken>> 리프레쉬 토큰 추가 및 갱신 기능 업데이트
  src/main/java/com/sparta/heartvera/domain/auth/controller/AuthController.java
  src/main/java/com/sparta/heartvera/domain/auth/dto/TokenRequestDto.java
  src/main/java/com/sparta/heartvera/domain/auth/dto/TokenResponseDto.java
  src/main/java/com/sparta/heartvera/domain/auth/service/AuthService.java
  src/main/java/com/sparta/heartvera/domain/user/entity/User.java
  src/main/java/com/sparta/heartvera/domain/user/repository/UserRepository.java
  src/main/java/com/sparta/heartvera/security/config/WebSecurityConfig.java
  src/main/java/com/sparta/heartvera/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/sparta/heartvera/security/util/JwtUtil.java
Labels: 🌟 feat

#29 [2024/06/20] refactor/swagger-exception >> 토큰 예외처리 및 필수 기능 리팩토링
  src/main/java/com/sparta/heartvera/common/exception/ErrorCode.java
  src/main/java/com/sparta/heartvera/config/SwaggerConfig.java
  src/main/java/com/sparta/heartvera/domain/auth/controller/AuthController.java
  src/main/java/com/sparta/heartvera/domain/auth/dto/SignupRequestDto.java
  src/main/java/com/sparta/heartvera/domain/auth/dto/TokenResponseDto.java
  src/main/java/com/sparta/heartvera/domain/auth/service/AuthService.java
  src/main/java/com/sparta/heartvera/domain/comment/controller/CommentController.java
  src/main/java/com/sparta/heartvera/domain/comment/service/CommentService.java
  src/main/java/com/sparta/heartvera/domain/post/controller/PostController.java
  src/main/java/com/sparta/heartvera/domain/post/controller/PublicPostController.java
  src/main/java/com/sparta/heartvera/domain/user/controller/UserController.java
  src/main/java/com/sparta/heartvera/domain/user/dto/UserPwRequestDto.java
  src/main/java/com/sparta/heartvera/domain/user/service/UserService.java
  src/main/java/com/sparta/heartvera/security/filter/ErrorResponseWriter.java
  src/main/java/com/sparta/heartvera/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/sparta/heartvera/security/filter/JwtAuthorizationFilter.java
  src/main/java/com/sparta/heartvera/security/util/JwtUtil.java
Labels: ♻️ refactor

#30 [2024/06/21] feat/follow >> 팔로우 기능 구현
  src/main/java/com/sparta/heartvera/common/exception/ErrorCode.java
  src/main/java/com/sparta/heartvera/domain/follow/controller/FollowController.java
  src/main/java/com/sparta/heartvera/domain/follow/dto/FollowRequestDto.java
  src/main/java/com/sparta/heartvera/domain/follow/dto/FollowResponseDto.java
  src/main/java/com/sparta/heartvera/domain/follow/entity/Follow.java
  src/main/java/com/sparta/heartvera/domain/follow/repository/FollowRepository.java
  src/main/java/com/sparta/heartvera/domain/follow/service/FollowService.java
  src/main/java/com/sparta/heartvera/domain/post/controller/PublicPostController.java
  src/main/java/com/sparta/heartvera/domain/post/repository/PublicPostRepository.java
  src/main/java/com/sparta/heartvera/domain/post/service/PublicPostService.java
  src/main/java/com/sparta/heartvera/domain/user/entity/User.java
  src/main/java/com/sparta/heartvera/domain/user/service/UserService.java
Labels: 🌟 feat

#35 [2024/06/23] feat/profile >> userService 단위테스트
  build.gradle
  src/test/java/com/sparta/heartvera/domain/user/service/UserServiceTest.java
Labels: 🌟 feat

#33 [2024/06/23] feat/backoffice >> 백오피스 기능 구현
  src/main/java/com/sparta/heartvera/domain/admin/controller/AdminController.java
  src/main/java/com/sparta/heartvera/domain/admin/service/AdminService.java
  src/main/java/com/sparta/heartvera/domain/auth/dto/LoginRequestDto.java
  src/main/java/com/sparta/heartvera/domain/comment/dto/PublicCommentResponseDto.java
  src/main/java/com/sparta/heartvera/domain/comment/service/CommentService.java
  src/main/java/com/sparta/heartvera/domain/post/dto/PublicPostResponseDto.java
  src/main/java/com/sparta/heartvera/domain/post/service/PostService.java
  src/main/java/com/sparta/heartvera/domain/post/service/PublicPostService.java
  src/main/java/com/sparta/heartvera/domain/user/entity/User.java
  src/main/java/com/sparta/heartvera/domain/user/service/UserService.java
  src/main/java/com/sparta/heartvera/security/config/WebSecurityConfig.java
  src/main/java/com/sparta/heartvera/security/util/JwtUtil.java
Labels: 🌟 feat

#31 [2024/06/21] refactor/swagger-exception >> 예외처리 코드 수정 및 signup 리팩토리
  src/main/java/com/sparta/heartvera/common/exception/ErrorCode.java
  src/main/java/com/sparta/heartvera/common/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/heartvera/domain/auth/controller/AuthController.java
  src/main/java/com/sparta/heartvera/domain/auth/dto/SignupResponseDto.java
  src/main/java/com/sparta/heartvera/domain/auth/dto/TokenResponseDto.java
  src/main/java/com/sparta/heartvera/domain/auth/service/AuthService.java
  src/main/java/com/sparta/heartvera/domain/user/repository/UserRepository.java
  src/main/java/com/sparta/heartvera/domain/user/service/UserService.java
  src/main/java/com/sparta/heartvera/security/filter/ErrorResponseWriter.java
Labels: ♻️ refactor

#38 [2024/06/24] feat/follow >> 팔로우 value/default값 추가
  src/main/java/com/sparta/heartvera/domain/post/controller/PublicPostController.java
Labels: ♻️ refactor

#23 [2024/06/20] feat/like >> 좋아요 기능 구현
  src/main/java/com/sparta/heartvera/config/SwaggerConfig.java
  src/main/java/com/sparta/heartvera/domain/comment/service/CommentService.java
  src/main/java/com/sparta/heartvera/domain/like/controller/LikeController.java
  src/main/java/com/sparta/heartvera/domain/like/dto/LikeCountResponseDto.java
  src/main/java/com/sparta/heartvera/domain/like/entity/Like.java
  src/main/java/com/sparta/heartvera/domain/like/entity/LikeEnum.java
  src/main/java/com/sparta/heartvera/domain/like/repository/LikeRepository.java
  src/main/java/com/sparta/heartvera/domain/like/service/LikeService.java
  src/main/java/com/sparta/heartvera/domain/post/service/PostService.java
  src/main/java/com/sparta/heartvera/domain/post/service/PublicPostService.java
  src/main/java/com/sparta/heartvera/domain/user/entity/User.java
Labels: 🌟 feat

#40 [2024/06/24] feat/follow >> 팔로우 예외처리 수정, page -1 수정
  src/main/java/com/sparta/heartvera/common/exception/ErrorCode.java
  src/main/java/com/sparta/heartvera/domain/follow/dto/FollowResponseDto.java
  src/main/java/com/sparta/heartvera/domain/follow/service/FollowService.java
  src/main/java/com/sparta/heartvera/domain/post/controller/PublicPostController.java
  src/main/java/com/sparta/heartvera/domain/post/service/PublicPostService.java
Labels: ♻️ refactor

#42 [2024/06/24] feat/post >> post 예외처리, page 수정
  src/main/java/com/sparta/heartvera/domain/post/controller/PostController.java
  src/main/java/com/sparta/heartvera/domain/post/controller/PublicPostController.java
  src/main/java/com/sparta/heartvera/domain/post/service/PostService.java
  src/main/java/com/sparta/heartvera/domain/post/service/PublicPostService.java
Labels: 🌟 feat

#41 [2024/06/24]Feat/kakaologin >> 소셜 로그인 구현
  src/main/java/com/sparta/heartvera/domain/auth/controller/AuthController.java
  src/main/java/com/sparta/heartvera/domain/auth/dto/SocialUserDto.java
  src/main/java/com/sparta/heartvera/domain/auth/service/KakaoService.java
  src/main/java/com/sparta/heartvera/security/config/WebSecurityConfig.java
  src/main/resources/application.properties
Labels: 🌟 feat

#47 [2024/06/24] feat/profile >> UserPwRequestDto 정규식 수정
  src/main/java/com/sparta/heartvera/domain/user/dto/UserPwRequestDto.java
Labels: 👾 bug

#48 [2024/06/24] feat/follow >> PublicPost 내가 팔로우한 사람 게시물 조회시 exception 수정
  src/main/java/com/sparta/heartvera/domain/post/controller/PublicPostController.java
  src/main/java/com/sparta/heartvera/domain/post/service/PublicPostService.java
Labels: ♻️ refactor
